---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "superSecretPassword"
  POSTGRES_USER: "optuna"
  POSTGRES_DB: "optunaDatabase"
  POSTGRES_MLFLOW_DB: "mlflowDatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-mlflow
spec:
  type: ClusterIP
  selector:
    app: postgres-mlflow
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-mlflow
  labels:
    app: postgres-mlflow
spec:
  selector:
    matchLabels:
      app: postgres-mlflow
  serviceName: postgres-mlflow
  template:
    metadata:
      labels:
        app: postgres-mlflow
    spec:
      containers:
        - name: postgres-mlflow
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
spec:
  type: ClusterIP
  selector:
    app: mlflow-server
  ports:
    - port: 5000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mlflow-server
  labels:
    app: mlflow-server
spec:
  selector:
    matchLabels:
      app: mlflow-server
  serviceName: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow-server
          image: optuna-kubernetes:example
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  parallelism: 5
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-database
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          command:
          - /bin/sh
          - -c
          - -e
          - -x
          - |
            until pg_isready -U $(POSTGRES_USER) -h postgres -p 5432;
            do echo "waiting for postgres"; sleep 2; done;
          envFrom:
            - secretRef:
                name: postgres-secrets
        - name: start-mlflow-server
          image: optuna-kubernetes:example
          imagePullPolicy: IfNotPresent
          command:
          - mlflow
          - server
          - --backend-store-uri postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_MLFLOW_DB)
          - --host 0.0.0.0
      containers:
        - name: worker
          image: optuna-kubernetes:example
          imagePullPolicy: IfNotPresent
          command:
            - python
            - sklearn_distributed.py
          envFrom:
            - secretRef:
                name: postgres-secrets
---
