name: Sphinx

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python_version: 3.8

    - name: Install
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[doctest,document]
        
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash
        
    - name: Cache Tutorial
      uses: actions/cache@v2
      with:
        path: docs/source/tutorial
        key: ${{ runner.os }}-${{ hashFiles('**/setup.py') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('**/setup.py') }}

    - name: Build Document
      run: |
        cd docs
        make html -j
        cd ../

    - uses: actions/upload-artifact@v2
      with:
        name: built-document
        path: docs/build

    - name: Run Doctest
      run: |
        cd docs
        make doctest -j
        cd ../
